### PR TITLE
Spelling of text was wrong,corrected it

### PR DESCRIPTION
**Pull request by sumitmukharjeeeeee**
twxt to text

### CODE REVIEW

**Review by CodingSpecies — APPROVED** [review]
LGTM! Thank you

**Comment by CodingSpecies** [comment]
I have sent an invite for you to join our organisation, please see below on how to accept, and make the badge public on your readme

**Comment by CodingSpecies** [comment]
@sumitmukharjeeeeee You have received an email to join, or press this link - https://github.com/App-Choreography - , and you'll see a banner, for you to join the organisation! 🎉 

You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
image

**Comment by CodingSpecies** [comment]
Welcome to app choreography!

**Comment by CodingSpecies** [comment]
@all-contributors please add @sumitmukharjeeeeee  for content

**Comment by sumitmukharjeeeeee** [comment]
I have a question can I contribute more to your repository.

**Comment by CodingSpecies** [comment]
@sumitmukharjeeeeee , yes you can!

**Pull request merged**
